<a href="https://colab.research.google.com/github/ialimustufa/MLFT/blob/master/Numpy_for_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Task 2 Solution**

In [1]:
def getsymbol() :
    x = input ("Enter your symbol : ")
    makepattern (x)

def makepattern (x) :

    for i in range (10) :
        if i < 6 :
              print ((10 - i) * ' ' + i * (x + ' '))
        else : 
              print ( i * ' ' + (10 - i) * (x + ' '))

getsymbol()

Enter your symbol : @
          
         @ 
        @ @ 
       @ @ @ 
      @ @ @ @ 
     @ @ @ @ @ 
      @ @ @ @ 
       @ @ @ 
        @ @ 
         @ 


# **What is a Python NumPy?**
NumPy is a Python package which stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object, provide tools for integrating C, C++ etc. It is also useful in linear algebra, random number capability etc. 

NumPy array can also be used as an efficient multi-dimensional container for generic data. Now, let me tell you what exactly is a python numpy array.

Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize numpy arrays from nested Python lists and access it elements.

### Installing Numpy Library

You install numpy library through pip in the following way.

`---> pip install numpy`

If you want a specific version you may do so in the following way.

`--> pip install numpy==< version number>`



In [2]:
# Installing Numpy Library

!pip install numpy

# **Overview**

In [3]:
# Importing the numpy library.
import numpy as np

# Initialising a numpy array.
arr = np.array([-1, 2, 5])

# Print the array
print(arr)

# Printing the representation of the array
print(repr(arr))

[-1  2  5]
array([-1,  2,  5])


In [4]:
#Single-dimensional Numpy Array:
import numpy as np
a=np.array([1,2,3])
print(repr(a))

array([1, 2, 3])


In [5]:
#Multi-dimensional Array:
a=np.array([(1,2,3),(4,5,6)])
print(repr(a))

array([[1, 2, 3],
       [4, 5, 6]])


**Python NumPy Array v/s List:**

We use python numpy array instead of a list because of the below three reasons:

1. Less Memory
2. Fast
3. Convenient

The very first reason to choose python numpy array is that it occupies less memory as compared to list. Then, it is pretty fast in terms of execution and at the same time it is very convenient to work with numpy. 

So these are the major advantages that python numpy array has over list.

In [6]:
import numpy as np

import time 
import sys

r = range(1000)
print (sys.getsizeof(r)*len(r))

a= np.arange(1000)
print(a.itemsize * a.size)

48000
8000


# **Numpy arrays**

Numpy arrays are basically just python list with added features. In fact, you can easily convert a python list to a NumPy arrays using <a href=https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html>np.arrays</a> function, which takes in a python list as its required argument. The function also has quite a few keyword arguments, but the main one is **dtype**. 
The dtype keyword argument takes in a NumPy type and manually casts the array to the specified data type. 


In [7]:
import numpy as np 

arr = np.array([[0, 1, 2], [3, 4, 5]])

print(repr(arr))

arr = np.array([[0, 1, 2], [3, 4, 5]],dtype=np.float32)

print(repr(arr))

array([[0, 1, 2],
       [3, 4, 5]])
array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


**NOTE:** When the elements of a NumPy array are of mixed types, the array's type will be upcasted to highest level type. This means that if an array input has mixed int or float elements, all integers will be casted to their floating point equivalent. 
If an array is mixed with int,float, and string elements everything is casted to string.

The below code is an example of the above said Note.

In [8]:
arr = np.array([0, 0.1, 2])
print(repr(arr))

array([0. , 0.1, 2. ])


**Copying in numpy array**

Similar to python list, when we make a refrence to a NumPy array it doesn't create a different array. Therefore, if we change a value using the refrence variable, it changes the original array as well. We get around this by using an array's inherent copy function. The function has no required arguments and it returns the copied array.

In the below code snippet, c is a refrence to a while d is a copy. Therefore, changing c leads to same change in a, while changing d doesn't change the value of b.

In [9]:
text = "My name is {name} , I am {age}".format ( name = "python" , age = 10) 
print (text)

text2 = "My name is {} , I am {}".format ( "python",10) 
print (text2)

text3 = "My name is {0} , I am {1}".format ( "python" , 10)
text3

My name is python , I am 10
My name is python , I am 10


'My name is python , I am 10'

In [10]:
# The first array
a = np.array([0, 1])

# The second array
b = np.array([9, 8])

# Refrencing
c = a
print('Array a: {0}'.format(repr(a)))
c[0] = 5
print('Array c: {0}'.format(repr(c)))
print('Array a: {0}'.format(repr(a)))

# Copying
d = b.copy()
d[0] = 6
print('Array b: {0}'.format(repr(b)))
print('Array d: {0}'.format(repr(d)))

Array a: array([0, 1])
Array c: array([5, 1])
Array a: array([5, 1])
Array b: array([9, 8])
Array d: array([6, 8])


**Casting in numpy array**

We can cast NumPy arrays through their inherent <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html">astype</a> function.
The required argument is the new type of the array. It returns the array cast to the new type.

The code below shows an example of casting using astype function. The <a href="">dtype</a> property returns the type of the array.


In [11]:
arr = np.array([0, 1, 2])
print (repr(arr))
print(arr.dtype)

arr = arr.astype(np.float32)
print (repr(arr))
print(arr.dtype)

array([0, 1, 2])
int64
array([0., 1., 2.], dtype=float32)
float32


# **NumPy Basics**
Perform basic operations to create and modify NumPy arrays.


**Ranged Data**

While np.array can be used to create any array, it is equivalent to hardcoding an array. This won't work when the array has hundreds of values. Instead NumPy provides an option to create ranged data arrays using np.arange . The function acts very similar to range function in Python, and will always return 1-D array.

The code below explains the usage of np.arange

In [12]:
import numpy as np

arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4.1)
print(repr(arr))

arr = np.arange(0, 10, 3)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1.,  0.,  1.,  2.,  3.,  4.])
array([0, 3, 6, 9])


The output of np.arange is spefied as follows:

* If only single number, lets say n is passed as an argument, np.arange will return an array with all the integers in the range[0,n). 
* For two arguments, m and n, np.arange will return an array with all the integers in the range [m,n).
* If three arguments are given lets say m, n, and s, np.arange will return an array with all the integers in the range(m,n) using a step size s.

NOTE: Like np.array, np.arange perform upcasting. It also has dtype keyword argument to manually cast the array.


**Linspace Function**

np.linspace(): 

To specify the number of element in the returned array, rather than step size we can use the np.linspace function. 

This function takes in a required first two arguments, for the start and end of the range, respectively. The end of the range is inclusive for np.linspace unless the keyword endpoint is set to False. 

To specify the number of elements we set the num keyword, its default value is 50.

The code below explaines the use of np.linspace.

In [13]:
arr = np.linspace(5, 10, num=4)
print(repr(arr))

arr = np.linspace(5, 10, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 10, num=4, dtype = np.int32)
print(repr(arr))

array([ 5.        ,  6.66666667,  8.33333333, 10.        ])
array([5.  , 6.25, 7.5 , 8.75])
array([ 5,  6,  8, 10], dtype=int32)


**Reshaping Data**

The function we use to reshape data in NumPy is np.reshape. It takes in an array and a new shape as required arguments. The new shape must exactly contain all the elements from the input array. For example, we could reshape an array with 12 elements to (4, 3), but we can't reshape it to (4, 4).

We are allowed to use the special value of -1 in at most one dimension of the new shape. The dimension with -1 will take on the value necessary to allow the new shape to contain all the elements of the array.

The code below shows example usages of np.reshape.

In [14]:
arr = np.arange(8)
print(repr(arr))
print (arr.shape)
print("\n")

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('\nNew shape: {}'.format(reshaped_arr.shape))



array([0, 1, 2, 3, 4, 5, 6, 7])
(8,)


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

New shape: (2, 4)


While the np.reshape function can perform any reshaping utilities we need, NumPy provides an inherent function for flattening an array. Flattening an array reshapes it into a 1D array. Since we need to flatten data quite often, it is a useful function.

The code below flattens an array using the inherent flatten function.

In [15]:
arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flattened shape: (8,)


**Transposing**

Similar to how it is common to reshape data, it is also common to transpose data. Perhaps we have data that's supposed to be in a particular format, but some new data we get is rearranged. We can just transpose the data, using the np.transpose function, to convert it to the proper format.

The code below shows an example usage of the np.transpose function. The matrix rows become columns after the transpose.


In [16]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('transposed shape: {}'.format(transposed.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
transposed shape: (2, 4)


**Zeros and Ones**

Sometimes, we need to create arrays filled solely with 0 or 1. For example, since binary data is labeled with 0 and 1, we may need to create dummy datasets of strictly one label. For creating these arrays, NumPy provides the functions np.zeros and np.ones. They both take in the same arguments, which includes just one required argument, the array shape. The functions also allow for manual casting using the dtype keyword argument.

The code below shows example usages of np.zeros and np.ones.


In [17]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones (5)
print (repr (arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

arr = np.identity(4)
print (repr(arr))

array([0., 0., 0., 0.])
array([1., 1., 1., 1., 1.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


# **Math** 
Understand how arithmetic and linear algebra work in NumPy



**Arithmetic**

One of the main purposes of NumPy is to perform multidimensional arithmetic. Using Numpy arrays, we can apply arithmetic to each element with a single operations.

The code below shows multi-dimensional arithmetic with NumPy


In [18]:
arr = np.array([[1,2], [3,4]])

print (repr(arr))

# Add 1 to element values
print(repr(arr + 1))

# Subtract element values by 1.2
print(repr(arr - 1.2))

# Double element values
print(repr(arr * 2))

# Half the element values
print(repr(arr / 2))

# Square element values
print(repr(arr ** 2))

# Square root element values
print(repr(arr**0.5))

array([[1, 2],
       [3, 4]])
array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


Some more operations in numpy such as to find the minimum, maximum as well the sum of the numpy array. 

In [19]:
import numpy as np
 
a= np.array([1,2,3])
print(repr(a.min()))
print(repr(a.max()))
print(repr(a.sum()))

1
3
6


There are various mathematical functions that can be performed using python numpy. You can find the square root, standard deviation of the array.

In [20]:
import numpy as np
a=np.array([(1,2,3)])
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356 1.73205081]]
0.816496580927726


**Non-Linear functions**

Apart from basic arithmetic operations, Numpy also allows you to use non-linear functions such as exponentials and logarithms.

The function np.exp performs a base e exponential on array while the function np.exp2 performs a base 2 exponential. Likewise np.log, np.log2, np.log10 all perform logarithms on an input array using base e, base2, base10 respectively.

The code below shows various exponentials and logarithms with NumPy. Note that np.e and np.pi represents mathematical constants e and π, respectively.

In [21]:
arr = np.array([[1, 2], [3, 4]])
# Raised to power of 3
print(repr(np.exp(arr)))
# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
# Natural logarithm
print(repr(np.log(arr2)))
# Base 10 logarithm
print(repr(np.log10(arr2)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


**Matrix Multiplication**

Since Numpy arrays are basically vectors and matrices, it makes sense that there are functions for dot products and matrix multiplication. Specifically, the main function to use is np.matmul, which takes two vector/matrix arrays as input and produces a dot product or matrix multiplication. 

The code below explains various examples of matrix multiplication. When both inputs are 1-D, the output is dot product.

Note that dimensions of the two input matrixes must be valid for a matrix multiplication. Specifically, the second dimensions of the first matrix must equal the first dimensions of the second matrix, otherwise np.matmul will result in a ValueError.


In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(repr(np.matmul(arr1, arr2)))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])

print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))
# This will result in ValueError
# print(repr(np.matmul(arr3, arr3)))

27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


# **Random Integers**

Similar to python random module, NumPy has its own submodule for  pseudo-random number generation called np.random. It provides all the necessary randomized operations and extends it to multi-dimensional arrays. 
To generate pseudo-random integers we use np.random.randint function.

The code below shows example of np.random.randint


In [23]:
import numpy as np

print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high=9))

random_arr = np.random.randint(-3, high=14,
                               size=(3, 3))
print(repr(random_arr))

4
1
8
array([[ 2,  0,  2],
       [-1, -3,  7],
       [ 9,  0, -3]])


# **Indexing**

Index into NumPy arrays to extract data and array slices


**Array accessing**

Accessing NumPy arrays is identical to accessing python list. For Multi-dimensional arrays it is equivalent to accessing Python list of lists.

The code below shows example how to access NumPy arrays


In [24]:
import numpy as np

arr = np.arange(5)
print(repr(arr))
print(arr[0])
print(arr[4])

arr = np.array([[6,3],[0,2]])
# subarray
print(repr(arr[0]))
print(arr[0][1])
print(arr[1][1])

array([0, 1, 2, 3, 4])
0
4
array([6, 3])
3
2


**Slicing**

Numpy arrays also support slicing. Similar to python we can use the colon operator for slicing. We can also use negative indexing to slice in the backwards direction.

The code below explains slices of 1-D NumPy array



In [25]:
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[-1:-4]))

print (repr (arr [ : : -1]))

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([], dtype=int64)
array([5, 4, 3, 2, 1])


# **Filtering** 

Filter NumPy data for specific values.

**Filtering data**

Sometimes we have data that contains values we dont want to use. For example, when tracking the best hitters in baseball, we may want to only use the batting average data above say 300. In this case, we should filter the overall data for only the values we want.

The key to filtering data is through basic relation operations, eg. ==, > , etc. In NumPy we can apply basic relation operations element wise on array.

The code below shows relation operations on Numpy arrays. The ~ operation represents a boolean negation, i.e. it flips each truth value in array.


In [26]:
arr = np.array([[0, 2, 3],
               [1, 3, -6],
               [-3, -2, 1]])

print(repr(arr ==3))
print("\n")

print(repr(arr > 0))
print("\n")

print(repr(arr != 1))
print("\n")

# Negated the previous step
print(repr(~(arr != 1)))

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])


array([[False,  True,  True],
       [ True,  True, False],
       [False, False,  True]])


array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])


array([[False, False, False],
       [ True, False, False],
       [False, False,  True]])


Something to note here is that np.nan can't be used with any relation operation. Instead we use np.isnan to filter the location of np.nan.

The code below uses np.isnan to determine which locations of the array contain np.nan values.

In [27]:
arr = np.array([[0,2, np.nan],
                [1, np.nan, -6],
                [np.nan, -2, 1]])

print (repr(arr))
print("\n")
print(repr(np.isnan(arr)))

array([[ 0.,  2., nan],
       [ 1., nan, -6.],
       [nan, -2.,  1.]])


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])


# **TASK 3**


**Question 1**

Create an identity 2d-array or matrix (with ones across the diagonal).

[ Hint: ** You can also use **np.identity() function ]



**Question 2**

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: np.matrix() function

**Question 3**

Reverse both the rows and columns of the above matrix.

Hint: You can use the transpose .T)

**Question 4**

Add + 1 to all the elements in the given matrix.

**Question 5**

Find the mean, standard deviation and sum of all elements in the given matrix nd6. nd6 = [[ 1 4 9 121 144 169] [ 16 25 36 196 225 256] [ 49 64 81 289 324 361]]

Use: .mean() function